from pydantic import BaseModel
from typing import Any, Dict, List, Optional


class Field(BaseModel):
    """Individual extracted field description."""

    name: str
    value: Any
    raw: Optional[Dict] = None


class ExtractionResult(BaseModel):
    """Structure holding the result of a document extraction."""

    document_type: Optional[str]
    fields: Dict[str, Any]


class RiskFlag(BaseModel):
    """Schema for a risk flag generated by the engine."""

    rule: str
    severity: str
    message: str
    details: Optional[Dict] = None


class WorkingPaperOut(BaseModel):
    """Response model for summaries produced by the LLM."""

    content: str


class DocumentOut(BaseModel):
    """Public representation of a stored document and its analysis."""

    id: int
    filename: str
    s3_key: str
    content_type: str
    metadata: Optional[Dict]
    extraction: Optional[ExtractionResult]
    risk_flags: Optional[List[RiskFlag]]

    class Config:
        orm_mode = True
