from sqlalchemy import Column, Integer, String, ForeignKey, Text, DateTime, func
from sqlalchemy.orm import relationship

from . import Base


class WorkingPaper(Base):
    """Stores a draft summary generated by the LLM for an engagement."""

    __tablename__ = "working_papers"

    id = Column(Integer, primary_key=True, index=True)
    content = Column(Text, nullable=False)
    engagement_id = Column(Integer, ForeignKey("engagements.id"), nullable=False)
    engagement = relationship("Engagement", back_populates="working_papers")

    created_at = Column(DateTime(timezone=True), server_default=func.now())
